<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    
    <modelVersion>4.0.0</modelVersion>

    <groupId>es.um.sisdist</groupId>
    <artifactId>SSDD-2425</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>backend/es.um.sisdist.backend.dao</module>
        <module>backend-rest/es.um.sisdist.backend.Service</module>
        <module>backend-grpc/es.um.sisdist.backend.grpc.GrpcService</module>
        <module>backend-grpc/es.um.sisdist.backend.grpc.GrpcServiceImpl</module>
         <module>backend-rest-externo</module> <!-- Este modulo es el que comento para poder funcionar, estando sin comentar da error el mvn clean install -DskipTest    -->
    </modules>

</project>
